- name: Copy container runtime repos for kubernetes nodes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {"src": docker-ce.repo.j2, "dest": /etc/yum.repos.d/docker-ce.repo, os: "CentOS"}
    - {"src": kubernetes.repo.j2, "dest": /etc/yum.repos.d/kubernetes.repo, os: "CentOS"}
    - {"src": sources.list.j2, "dest": /etc/apt/sources.list, os: "Ubuntu"}
    - {"src": sources.list.debian.j2, "dest": /etc/apt/sources.list, os: "Debian"}
    - {"src": docker-ce.repo.j2, "dest": /etc/yum.repos.d/docker-ce.repo, os: "Rocky"}
    - {"src": kubernetes.repo.j2, "dest": /etc/yum.repos.d/kubernetes.repo, os: "Rocky"}
    - {"src": docker-ce.repo-openEuler.j2, "dest": /etc/yum.repos.d/docker-ce.repo, os: "openEuler"}
    - {"src": kubernetes.repo.j2, "dest": /etc/yum.repos.d/kubernetes.repo, os: "openEuler"}
  when:
    - ansible_distribution == item.os

- name: Add docker, kubernetes and helm gpgs
  apt_key:
    url: "{{ item }}"
  loop:
    - https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
    - https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
  when:
    - ansible_distribution == 'Ubuntu' or
      ansible_distribution == 'Debian'

- name: Update kubernetes source before used
  apt:
    update_cache: yes
  when:
    - ansible_distribution == 'Ubuntu' or
      ansible_distribution == 'Debian'
