---
- name: Gather facts
  setup:

- name: Ensure localhost in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*"
    line: "127.0.0.1 localhost"
    state: present
  become: True

- name: Set system's hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when:
    # all-in-one 部署的场景不修改主机名
    - inventory_hostname != "localhost"

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in groups['baremetal'] %}
        {% set api_interface = hostvars[host]['api_interface'] %}
        {{ hostvars[host]['ansible_' + api_interface]['ipv4']['address'] }} {{ hostvars[host]['ansible_hostname'] }}
        {% endfor %}
  become: True

- name: Install epel-release packages
  yum:
    name: epel-release
    state: present
  when:
    - inventory_hostname in groups['kubernetes']
    - ansible_distribution == 'CentOS'

- name: Install dependent packages for kubernetes nodes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ common_dependent_packages }}"
  when:
    - inventory_hostname in groups['kubernetes']

- name: Change state of selinux
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  become: true
  when:
    - change_selinux | bool
    - inventory_hostname in groups['baremetal']
    - ansible_distribution == 'CentOS'

# Try to stop and disable delegated service,
# let it go when not exists.
- name: Disable firewalld service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  failed_when: false
  loop: "{{ services_to_disabled }}"
  when:
    - inventory_hostname in groups['baremetal']
    - ansible_distribution == 'CentOS'

- name: Disable ufw service
  service:
    name: ufw
    state: stopped
    enabled: False
  failed_when: false
  when:
    - inventory_hostname in groups['baremetal']
    - ansible_distribution == 'Ubuntu'

- name: Obtain the network card name
  set_fact:
    nic_name: "{{ ansible_interfaces[1] }}"

- name: Modify the network card name
  lineinfile:
    path: /etc/kubez/globals.yaml
    line: "network_interface: \"{{ nic_name }}\""
    regexp: '^#network_interface: "eth0"$'
  when:
    - ansible_interfaces[1] != 'eth0'
