---
# 后续优化
- name: Install {{ name }} chart applications
  helm_toolbox:
    name: "{{ name }}"
    namespace: "{{ namespace }}"
    state: present
    repository: "{{ repository}}"
    chart: "{{ chart }}"
    chart_extra_vars: "{{ chart_extra_vars }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True
  when: chart_enabled | bool
