---
- name: Include etcdctl_present.yaml
  include_tasks: etcdctl_present.yml

- name: Include local.yaml
  include_tasks: local.yaml
  when: etcd_backup_local | bool

- name: Include minio.yaml
  include_tasks: minio.yaml
  when: etcd_backup_minio | bool
