---
# NOTE(caoyingjun): The helm3 installation for centos is so rough.
# It must will be optimised later.
- name: Apply helm3 command immediately for CentOS
  script: setup_helm.sh "{{ helm_image }}"
  changed_when: false
  when:
    - enable_helm | bool
    - inventory_hostname in groups['kube-master']
    - ansible_distribution == 'CentOS'

# Install helm3 from apt repo for Ubuntu
- name: Install helm3 command immediately for Ubuntu
  apt:
    name: helm="{{ helm_release }}-1"
    update_cache: yes
  when:
    - enable_helm | bool
    - inventory_hostname in groups['kube-master']
    - ansible_distribution == 'Ubuntu'

# Use helm-apply role to install helm chart applications
- name: Install chart applications by helm-apply
  include_role:
    role: helm-apply
  vars:
    name: "{{ charts[item.name].name }}"
    namespace: "{{ charts[item.name].namespace }}"
    repository: "{{ charts[item.name].repository }}"
    chart: "{{ charts[item.name].chart }}"
    chart_extra_vars: "{{ charts[item.name].chart_extra_vars }}"
    chart_extra_flags: "{{ charts[item.name].chart_extra_flags }}"
    chart_enabled: "{{ item.enabled }}"
  loop: "{{ enable_charts }}"
