---
# NOTE(caoyingjun): The helm3 installation for centos is so rough.
# It must will be optimised later.
- name: Apply helm3 command immediately for CentOS
  script: setup_helm.sh "{{ helm_image }}"
  changed_when: false
  when:
    - enable_helm | bool
    - inventory_hostname in groups['kube-master']
    - ansible_distribution == 'CentOS'

# Install helm3 from apt repo for Ubuntu
- name: Install helm3 command immediately for Ubuntu
  apt:
    name: helm=3.5.2-1
    update_cache: yes
  when:
    - enable_helm | bool
    - inventory_hostname in groups['kube-master']
    - ansible_distribution == 'Ubuntu'

- name: Copy Fluentd-Elasticsearch applications
  copy:
    src: fluentd-elasticsearch
    dest: "{{ kube_application_dir }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  register: fe_result
  when: enable_fluentd_elasticsearch | bool
  run_once: True

- name: Apply Fluentd-Elasticsearch applications
  kube_toolbox:
     module_name: kubectl
     module_args: "apply -f {{ item }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True
  when:
    - enable_fluentd_elasticsearch | bool
    - fe_result.changed
  loop:
    - "{{ kube_application_dir }}/fluentd-elasticsearch"

- name: Install prometheus chart applications
  helm_toolbox:
    name: "{{ prometheus.name }}"
    namespace: "{{ prometheus.namespace }}"
    state: present
    repository: "{{ prometheus.repository }}"
    chart: "{{ prometheus.chart }}"
    chart_extra_vars: "{{ prometheus.chart_extra_vars }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True
  when: enable_prometheus | bool

# Use helm-apply role to install helm chart applications
- name: Install chart applications by helm-apply
  include_role:
    role: helm-apply
  vars:
    name: "{{ prometheus.name }}"
    namespace: "{{ prometheus.namespace }}"
    repository: "{{ prometheus.repository }}"
    chart: "{{ prometheus.chart }}"
    chart_extra_vars: "{{ prometheus.chart_extra_vars }}"
    chart_enabled: "yes"
