---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate YAML files
        run: yamllint -s .

      - name: Install flake8
        run: pip install flake8

      - name: Validate python files
        run: flake8
