---
name: deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: bash tools/setup_env.sh
